### ISSUE TITLE
addDecorator breaks `open canvas in new tab` for all stories

### ISSUE THREAD

**Issue by uberman4740** [JumboInteractiveLimited/storybook-addon-emotion-theme#10]
Hi, adding the addDecorator(themes) in the config.js of storybook breaks `open canvas in new tab` for all stories.

 On clicking the `open canvas in new tab` nothing shows up in the new tab for any story.
![image](https://user-images.githubusercontent.com/16237246/63874739-f4174380-c976-11e9-9ff0-6e28620198a3.png)

**Comment by tims-j** [comment]
Hey uberman, the addon-emotion-theme has only been tested with storybook versions < 5.x.x. You are welcome to create a PR as it is not being actively worked on anymore.
