### ISSUE TITLE
Warning: Removing a style property during rerender

### ISSUE THREAD

**Issue by mkhbragg** [JumboInteractiveLimited/storybook-addon-emotion-theme#21]
Thank you for this addon! It has been very helpful.

One minor issue: when switching between themes, I see this warning in the console:

![warning-storybook](https://user-images.githubusercontent.com/5139784/76684482-c4621d00-65e2-11ea-8fe3-02d62a56885f.gif)

**Comment by mkhbragg** [comment]
PR with fix: https://github.com/JumboInteractiveLimited/storybook-addon-emotion-theme/pull/22

**Comment by tims-j** [comment]
Hey @mkhbragg, you're welcome to fork this repo as it is no longer being actively developed.
