### ISSUE TITLE
Emotion 11 support

### ISSUE THREAD

**Issue by jezzgoodwin** [JumboInteractiveLimited/storybook-addon-emotion-theme#31]
Hi,

The current version of this library unfortunately doesn't support Emotion 11. The reason is that with version 11 there have been some package renames. Crucially the referenced package `emotion-theming` in `ThemeProvider.tsx` needs to now be `@emotion/react`.

Is it possible for an update to be made with this change?

Many thanks

**Comment by tims-j** [comment]
Hey @jezzgoodwin, you're more than welcome to fork this repo and make any changes you require. This project is no longer in active development and has stopped being supported.
