### ISSUE TITLE
Security vulnerability because of node-fetch

### ISSUE THREAD

**Issue by jezzgoodwin** [JumboInteractiveLimited/storybook-addon-emotion-theme#32]
Hi,

I am using this library in one of my projects hosted on GitHub. GitHub has recently enabled Dependabot which looks for vulnerable libraries and I recently received an alert. The problem package is node-fetch and it is included because of the following dependency chain:

storybook-addon-emotion-theme > recompose > fbjs > isomorphic-fetch > node-fetch

The next dependency in the chain is recompose, but unfortunately this library is no longer being updated. So it looks like the fix may be slightly more tricky than simply updating a library version.

Many thanks for this library :-)

**Comment by tims-j** [comment]
Hey @jezzgoodwin, you're more than welcome to fork this repo and make any changes you require. This project is no longer in active development and has stopped being supported.
